### ISSUE TITLE
Python3 Migration and Deluge 2.x support

### ISSUE THREAD

**Issue by shadowbq** [nicklan/Deluge-Pieces-Plugin#23]
Its time to support Deluge 2.x and Python 3. Python 2.x is dead.. 

https://pythonclock.org/ --  01 Jan 2020
https://github.com/python/devguide/pull/344

**Comment by nicklan** [comment]
I'm not really working on this plugin much anymore due to lack of time.  PR's are welcome (i'll be better about review+merge)

**Comment by akabhirav** [comment]
It does not look like the migration guide on the Deluge website is complete. I tried building the package using their migration guide using Python3.6. The egg was created but the plugin did not enable. Digging deeper it said that the core module is missing from the plugin.

It could be I have missed something. I'll update here if I can fix it

**Comment by Daniel-Marynicz** [comment]
I added support for deluge 2.x and Python 3 in pull request #24 :)

**Comment by Daniel-Marynicz** [comment]
@nicklan  I creared a new pull request #24  for this issue.

Current appearance on my Ubuntu 20.04 :)
![Zaznaczenie_0139](https://user-images.githubusercontent.com/1453265/87860987-2ee4ea00-c942-11ea-9dfb-93935880ca16.png)

**Comment by akxer** [comment]
I tried it too, it's working wonderfully. Thanks, @Daniel-Marynicz for the hard work.

**Comment by alpe12** [comment]
I get this error when trying to enable the plugin on my Odroid N2 (ubuntu minimal) via Windows 10:

> 21:13:26.822 [ERROR   ][deluge.pluginmanagerbase      :1469] Namespace Gtk not available
> Traceback (most recent call last):
>   File "/media/disk/temp/deluge/deluge/pluginmanagerbase.py", line 148, in enable_plugin
>     instance = cls(plugin_name.replace('-', '_'))
>   File "/media/disk/.config/deluge/plugins/Pieces-0.6-py3.8.egg/pieces/__init__.py", line 46, in __init__
>     from .core import Core as _plugin_cls
>   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
>   File "<frozen zipimport>", line 259, in load_module
>   File "/media/disk/.config/deluge/plugins/Pieces-0.6-py3.8.egg/pieces/core.py", line 49, in <module>
>     from .colors import Colors
>   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
>   File "<frozen zipimport>", line 259, in load_module
>   File "/media/disk/.config/deluge/plugins/Pieces-0.6-py3.8.egg/pieces/colors.py", line 40, in <module>
>     from .color import Color
>   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
>   File "<frozen zipimport>", line 259, in load_module
>   File "/media/disk/.config/deluge/plugins/Pieces-0.6-py3.8.egg/pieces/color.py", line 42, in <module>
>     gi.require_version("Gtk", "3.0")
>   File "/usr/lib/python3/dist-packages/gi/__init__.py", line 129, in require_version
>     raise ValueError('Namespace %s not available' % namespace)
> ValueError: Namespace Gtk not available

**Comment by Daniel-Marynicz** [comment]
You need install python3-gi and gtk3 bindings 
probably with command 
```
sudo apt install python3-gi gobject-introspection gir1.2-gtk-3.0
```

**Comment by dredkin** [comment]
Now I can see that Deluge 2.x support is integrated in the sources. I've built the .egg from this repository and it works fine with my Deluge client 2.0.3 on Windows.
SI I guess the time has come to make a new release, put it into https://github.com/nicklan/Deluge-Pieces-Plugin/downloads and update the info about 2.x compatibility on the https://dev.deluge-torrent.org/wiki/Plugins page.

If I wouldn't miss this plugin so much on 2.x that I decided to migrate it myself I'd never go to this page and wouldn't read the compatibility already implemented.

**Comment by jnqnfe** [comment]
Please do update the wiki.

**Comment by varad03** [comment]
Hey guys,
It's been a while and there hasn't been any update. 
Not to rush things along, but I can not for the life of me find even a test build supporting Deluge 2.x
The Downloads page is at v0.5.

@Daniel-Marynicz or @dredkin, could either of you please share your .egg in the meanwhile?

**Comment by UnPossible-Me** [comment]
Hey guys,
I don't want to rush things along, but it's been awhile since an update, and I can not for the life of me find even a test build for sorts for Deluge 2.x. 
The downloads page, deluge forum and website are all at v0.5

@Daniel-Marynicz or @dredkin, could either of you share your .egg in the meanwhile?

**Comment by alpe12** [comment]
[Pieces-0.6-py3.8.zip](https://github.com/nicklan/Deluge-Pieces-Plugin/files/7802776/Pieces-0.6-py3.8.zip)

You need this too:


> You need install python3-gi and gtk3 bindings probably with command
> 
> ```
> sudo apt install python3-gi gobject-introspection gir1.2-gtk-3.0
> ```

**Comment by UnPossible-Me** [comment]
Thank You!
